Geometry/gribova
PM-91-2/cross_ttd pull request #24
Opened 2023-03-07 13:02 UTC by jaron-sein

Исправлен интерфейс. Убран аргумент позиции в конструкторе, Исправлена реализация PathData (ранее Output)

2023-03-07 13:09 UTC, shemetovElisey approved these changes

2023-03-07 13:10 UTC, pysijuice requested changes

2023-03-07 13:10 UTC, pysijuice commented on Logic/obj/Logic.csproj.nuget.g.targets
> +<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
Уберите лишние файлы

2023-03-07 13:10 UTC, pysijuice commented on Geometry/Rectangle.cs
> +	public class Rectangle : IFigure
Разный код стайл

2023-03-07 13:10 UTC, pysijuice commented on Geometry/Rectangle.cs
> +			List<Vector2> M = new List<Vector2> {
название коллекции не отображает своей сути

2023-03-07 13:11 UTC, pysijuice commented on Geometry/Rectangle.cs
> +
лишняя строка

2023-03-07 13:12 UTC, pysijuice commented on Geometry/Matrix2x2.cs
> +			}
Line space между методами

2023-03-07 13:12 UTC, pysijuice commented on Geometry/Rectangle.cs
> +		}
line space

2023-03-07 13:12 UTC, pysijuice commented on Geometry/Rectangle.cs
> +		public void Move(Vector2 startPosition, Vector2 newPosition)
line space

2023-03-07 13:16 UTC, pysijuice commented on Geometry/IFigure.cs
> +		bool IsPointInFigure(Vector2 point, float eps);
отделение полей от методов

2023-03-07 13:25 UTC, pysijuice commented on Geometry/Rectangle.cs
> +		// Методы
Комментарий на методы, что это методы излишне

2023-03-07 15:45 UTC, pysijuice commented on Geometry/Rectangle.cs
> -			// Порядок точек: левая верхняя, левая нижняя, правая верхняя, правая нижняя
Этот комментарий был вполне осмыслен

2023-03-07 16:27 UTC, pysijuice commented on Logic/obj/Debug/net7.0/Logic.AssemblyInfo.cs
> -//     the code is regenerated.
Нужно убрать именно изменения файла, а не удалить его совсем

2023-03-08 15:34 UTC, pysijuice approved these changes

2023-03-08 15:40 UTC, merged